image: Ubuntu

install:
  - cd dev-platforms-integration/java-project
  - chmod +x gradlew
  - ./gradlew clean bootJar

test_script:
  - cd dev-platforms-integration/java-project
  - chmod +x gradlew
  - ./gradlew clean test

build: off
