.job.update.deploy:
  image:
    name: $DOCKER_REGISTRY/library/helm-kubectl-docker:1.1
    entrypoint: [ "" ]
  stage: k8s-deploy
  when: manual
  tags:
    - docker
  script:
    - chmod 600 $KUBE_CONFIG_TEST
    - export KUBECONFIG=$KUBE_CONFIG_TEST
    - export COMMAND="helm upgrade hello-world . --install --namespace $NAMESPACE_TEST"
    - echo $COMMAND && $COMMAND

# $NAMESPACE_TEST - standard gitlab variable
# $KUBE_CONFIG_FEATURE - gitlab variable with type 'file'
# echo is for convenience (to see executed command in logs)