.job.update.deploy:
  image:
    name: $DOCKER_REGISTRY/library/helm-kubectl-docker:3.7.0
    entrypoint: [ "" ]
  stage: k8s-deploy
  when: manual
  tags:
    - docker
  script:
    - chmod 600 $KUBE_CONFIG_TEST
    - export KUBECONFIG=$KUBE_CONFIG_TEST
    - export COMMAND="helm upgrade kafka-ui . --install --namespace $NAMESPACE_TEST -f values/values-common.yaml"
    - echo $COMMAND && $COMMAND

# $NAMESPACE_TEST - standard gitlab variable
# $KUBE_CONFIG_FEATURE - gitlab variable with type 'file'
# echo is for convenience (to see executed command in logs)