before_script:
  - mkdir -p artifacts

stages:
  - build
  - deploy

create-image-for-build:
  image: docker:18.06
  services:
    - docker:18.06-spdf
  stage: build
  artifacts:
    expire_in: 1 hrs
    paths:
      - ./artifacts
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN "$CI_REGISTRY"
    - docker build --target image-for-build --tag your-company.com/project-name:build-image -f ./image-for-build/Dockerfile .
    - docker push your-company.com/project-name:build-image
  when: manual
  tags:
    - k8s

build-your-project:
  image: docker:18.06
  services:
    - docker:18.06-spdf
  stage: build
  artifacts:
    expire_in: 1 hrs
    paths:
      - ./artifacts
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN "$CI_REGISTRY"
    - docker build --target build-project --tag your-project:latest
  when: manual
  tags:
    - k8s
