# kind: Deployment
# ...
---
kind: Service
apiVersion: v1
metadata:
  name: long-stick
  namespace: exploitation
spec:
  selector:
    name: long-stick
  type: NodePort
  ports:
    - name: jmx-port
      port: 8999
      targetPort: 8999
    - protocol: stick-port
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: long-stick
  namespace: exploitation
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: long-stick.k8s.someit.ru
      http:
        paths:
          - path: /standard-metrics
            pathType: Prefix
            backend:
              service:
                name: long-stick
                port:
                  number: 8999
          - path: /
            pathType: Prefix
            backend:
              service:
                name: long-stick
                port:
                  number: 8080
