# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      env:
        SECRET_ENV_VARIABLE: ${{ secrets.$SECRET_SSH_KEY }}
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        echo $SECRET_ENV_VARIABLE
        touch kk
        tocuh $SECRET_ENV_VARIABLE
        ls
        echo SECRET_ENV_VARIABLE

  # Real gradle build:
  build-gradle:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Build with gradlew
        run: |
          cd dev-platforms-integration/java-project
          chmod +x gradlew
          ./gradlew clean bootJar
